#!/bin/bash

	sudo wget http://nginx.org/keys/nginx_signing.key
	sudo apt-key add nginx_signing.key
	echo "
	deb http://nginx.org/packages/mainline/ubuntu/ trusty nginx
        deb-src http://ngixn.org/packages/mainline/ubuntu/ trusty nginx"
        > /etc/apt/sources.list 
	
       # sudo apt-get remove nginx-common
	# sudo apt-get update
	# sudo apt-get install nginx
	#sudo fuser -k 80/tcp
#	sudo nginx


